### ISSUE TITLE
Auto render in time interval

### ISSUE THREAD

**Issue by TheSkinnyRat** [TheSkinnyRat/antris#45]
Suggest auto re-render in time interval ex: auto render every 15 second in realtime data like queue status, hospital status and appointment status.

1. user queue status
![image](https://user-images.githubusercontent.com/26319163/147297274-79482ea9-80dc-4795-a7ea-5cd1908c54dc.png)

2. Hospital dashboard status
![image](https://user-images.githubusercontent.com/26319163/147297329-dd8b1de0-26cb-4628-89bb-9887deae6f7a.png)

3. Appointment queue
![image](https://user-images.githubusercontent.com/26319163/147297351-625c1b44-3bc7-4200-8f66-58dc86d90627.png)

4.

**Comment by MrOMadness** [comment]
udah gua push di branch 'fix-issues'. coba cekin lagi ya bang berfungsi atau engga, terutama yang di poin 3. kaya mungkin banget error, takutnya gua galiat. kalo udah oke langsung merge ke main aja. btw kalo ada apa" wa gua aja ya jgn discord. tenks bang
